### ISSUE TITLE
README should be in present tense and slightly simplified

### ISSUE THREAD

**Issue by AliciaMstt** [cristoichkov/Tareas_BioinfRepro2019_CCS#10]
Your README looks good. Congratulations. It could improve with the following:

* Write in present tense: "this is here", instead of "this will be here".

* Images are cool for the short summary of the project, but unnecessary in the README

* You don't need to copy part of the script that does something, just clearly state where (path) is this script and what does it does. Same for each directory.

**Comment by cristoichkov** [comment]
I have solved the recommendations, I hope they are well.  My mark of the fourth delivery of advances was five, but you didn't send me my errors.

**Comment by AliciaMstt** [comment]
Your mark was 5 because you didn't track your progress using the Github proyect tool, and the 4th delivery was about using it and showing at least 50% progress. 

![image](https://user-images.githubusercontent.com/5412404/55369664-b7711a00-54b4-11e9-9f8f-b45eeea7218d.png)
