### ISSUE TITLE
Project needs to have better task descriptions

### ISSUE THREAD

**Issue by AliciaMstt** [cristoichkov/Tareas_BioinfRepro2019_CCS#6]
I like that you made an issue for every task. Well done! However, I think you could improve your Project by not only stating the name of the file for each task, but to give a short description of the task. For example: Generate README, instead of Readme.rm

**Comment by cristoichkov** [comment]
Hi, I've already done the changes you suggested. I described the task in more detail. I want to make an interactive PCA, map and table in shiny dashboard.

**Comment by AliciaMstt** [comment]
Looks good.
